apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: group-3-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: kbazaar-api
          image: ghcr.io/kbtg-kampus-classnest-se-java/workshop-group-3:248a114128c71e44e4f1f62d16cbe182d3272124
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.password
            - name: ENABLED_FEATURE_PROMOTION_LIST_API
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: enabled.feature.promotion.list.api
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
